name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build e push da imagem Docker
      uses: docker/build-push-action@v5
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          jmarcelotse/projeto-tivit-cloud:v${{ github.run_number }}
          jmarcelotse/projeto-tivit-cloud:latest

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configuração do contexto Kubernetes
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG_AZ }}

    - name: Verificar contexto atual do Kubernetes (depuração)
      run: kubectl config current-context

    - name: Listar nós do Kubernetes (depuração)
      run: kubectl get nodes

    - name: Implantação no Kubernetes
      uses: Azure/k8s-deploy@v5
      with:
        manifests: ./k8s/deployment.yaml
        images: jmarcelotse/projeto-tivit-cloud:v${{ github.run_number }}
